# Generated by Django 6.0.2 on 2026-02-15 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('education', 'Education'), ('health', 'Health'), ('agriculture', 'Agriculture'), ('employment', 'Employment'), ('housing', 'Housing'), ('women', 'Women Empowerment'), ('startup', 'Startup'), ('pension', 'Pension')], max_length=50)),
                ('income_limit', models.FloatField(blank=True, null=True)),
                ('residence_type', models.CharField(blank=True, choices=[('urban', 'Urban'), ('rural', 'Rural')], max_length=10, null=True)),
                ('eligible_categories', models.CharField(blank=True, max_length=50, null=True)),
                ('min_age', models.IntegerField(blank=True, null=True)),
                ('max_age', models.IntegerField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('govt_type', models.CharField(choices=[('central', 'Central Government'), ('state', 'State Government')], max_length=20)),
                ('official_link', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
